<Project Sdk="Godot.NET.Sdk/4.5.1">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <NoWarn>IDE0130,IDE0160</NoWarn> <!-- Disable namespace folder structure matching -->
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Godot.Extension\Godot.Extension.csproj" />
    <ProjectReference Include="..\Module\BfresLibrary\BfresLibrary\BfresLibrary.csproj" />
    <ProjectReference Include="..\MoonFlow.Project\MoonFlow.Project.csproj" />
    <ProjectReference Include="..\Nindot\Nindot.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ByteSize" Version="2.1.2" />
  </ItemGroup>
</Project>